### ISSUE TITLE
Несколько вопросов по сборке

### ISSUE THREAD

**Issue by feedlike** [lbrdev/z390-e_OC_Hackintosh#1]
- Планируется ли в будущем выкладывать гайд и настройки по Big Sur?
- Type C корректно ли работает? Возможен вывод изображения по нему на монитор?

**Comment by lbrdev** [comment]
Привет! Это моя рабочая сборка, которой я сам пользуюсь каждый день, поэтому Big Sur будет, но уже ближе к стабильным версиям системы.
По поводу USB-C - в данной сборке он отключён, так как я сам им не пользуюсь, да и с ним портов в системе больше 15. Но включить его можно, изменив пару строк в USB-Map.kext по желанию. Это должно сработать. Его предполагаемый идентификатор есть в map-table. Что касается его функционала для вывода изображения - здесь пожалуй все однозначнее, этот порт не Thunderbolt, а обычный Type-C USB 3.1 Gen 2 (по инфе с официального сайта). Поэтому он не предназначен для вывода изображения, только для передачи данных.

**Comment by feedlike** [comment]
Спасибо большое за информацию. а NVRAM работает за счет таблицы которые подсовываешь опенкору?

И ещё вопрос про сон и пробуждение - все ли стабильно и корректно работает?

И много ли нужно делать изминений для карты Sapphire NITRO+ RX 5700 XT ?
