### ISSUE TITLE
update opencore for 0.6.3?

### ISSUE THREAD

**Issue by dong-qian** [lbrdev/z390-e_OC_Hackintosh#2]
Hi, thanks for the EFI.
Any plan to update the opencore to 0.6.3?

BTW I have one question related to M.2 slots setup. Do I need to do the same thing in the bios like the image you showed to us if I use both slots? one for macOS, one for windows.

**Comment by lbrdev** [comment]
@qiandongyq hi!

I've delayed update till Big Sure release. Update will be soon with migrate to MacOS 11.0.1.

**Comment by dong-qian** [comment]
@lbrdev really appreciated.

**Comment by lbrdev** [comment]
@qiandongyq about m2.
Just disable SATA6G_56 (**Onboard Devices Configuration** -> **PCIEX16_3 Bandwidth**) in BIOS settings.

From [manual](https://dlcdnets.asus.com/pub/ASUS/mb/LGA1151/ROG_STRIX_Z390-E_GAMING/E14841_ROG_STRIX_Z390-E_GAMING_UM_V2_WEB.pdf):
```
PCIEX16_3 Bandwidth
[X2 Mode] Run at X2 mode with SATA6G_56 enabled.
[X4 Mode] Run at X4 mode for higher performance with SATA6G_56 disabled.
```

[Here](https://rog.asus.com/forum/showthread.php?107904-Asus-Z390-F-Gaming-M-2-NVMe-PCI-E-SATA-slot-disablement) is some details.
