### ISSUE TITLE
Rebooting after logotype show

### ISSUE THREAD

**Issue by kamil-bednarek** [lbrdev/z390-e_OC_Hackintosh#3]
Makes BIOS config as you mentioned, also prepared OSX  Big Sur as mentioned in tutorial.
Now I see only apple logotype and reeboot cycle :(

Having the same hardware config as described.

**Comment by lbrdev** [comment]
@kamillo1888 You should leave a log with debugging mode to help you. This repository is a working copy of system from my device from which I am writing this message...

**Comment by lbrdev** [comment]
Closed after a month
