### ISSUE TITLE
Question about the opencore version

### ISSUE THREAD

**Issue by dong-qian** [lbrdev/z390-e_OC_Hackintosh#4]
Hi,
Do you know how to check my current opencore version ? I used your EFI and it supposes to 0.7.1 ?  
but when I run `nvram 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102:opencore-version`, it shows `REL-063-2020-11-02`, looks like it still on 0.63. Thanks

**Comment by lbrdev** [comment]
Hi!
Check [this](https://github.com/acidanthera/bugtracker/issues/1539) issue in acidanthera repo. May help. Good luck!

**Comment by dong-qian** [comment]
Thanks, fixed
