### ISSUE TITLE
Are you able to use sidecar wireless with the FenviT919?

### ISSUE THREAD

**Issue by zercarrt** [lbrdev/z390-e_OC_Hackintosh#5]
I just bought a Fenvit919 card, everything works on my EFI but not sidecar (wireless)
- I just tried yours but Im not really sure if im doing something wrong or it just doesn't work.

**Comment by lbrdev** [comment]
Hi, sorry but I don't have iPad that matches requirements for Sidecar test.
I've got mini 4.

**Comment by zercarrt** [comment]
Oh! It's okay. Thanks anyways for replying
