### ISSUE TITLE
Wondering if you are preparing a buil for OSX Ventura 

### ISSUE THREAD

**Issue by sirCamp** [lbrdev/z390-e_OC_Hackintosh#6]
I'm curious to know if you are moving to Ventura and if you tried to move the build to it.
Great work with Monterey!

**Comment by joslin1215** [comment]
本人利用宽带的漏洞开通QQ业务：会员（成长值5点），蓝、黄、绿、红、钻、QQ堂紫钻 、QQ音速紫钻（成长值均为12点）开通一项20元，2项35元，3项50元，开通4项以上每项均以15元计算，这个只赚大家一点手续费，另外想开ＱＱ炫舞紫钻的另加２５元，因为每个宽带账号可以透支200元，而且一个账号绑定一个ＱＱ号，想要开通的加我的QQ376719443

**Comment by lbrdev** [comment]
@sirCamp Hi!
At the moment, development is suspended due to change of hardware.
But you can do it yourself by following the instruction in Readme.

**Comment by joslin1215** [comment]
本人利用宽带的漏洞开通QQ业务：会员（成长值5点），蓝、黄、绿、红、钻、QQ堂紫钻 、QQ音速紫钻（成长值均为12点）开通一项20元，2项35元，3项50元，开通4项以上每项均以15元计算，这个只赚大家一点手续费，另外想开ＱＱ炫舞紫钻的另加２５元，因为每个宽带账号可以透支200元，而且一个账号绑定一个ＱＱ号，想要开通的加我的QQ376719443
